# Site settings
title: Ruby Pixel
email: michael@nervd.com
description: "Blog for ruby, nodejs, docker, javascript, front-end development, and other web technologies."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.rubypx.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  malet

# Build settings
markdown: kramdown
